export {default as Login} from './Login/Login';
export {default as Home} from './Home/Home';
export {default as Signup} from './Signup/Signup';
export {default as ForgotPassword} from './ForgotPassword/ForgotPassword';
export {default as NavBar} from './NavBar/NavBar';
export {default as MyPosts} from './MyPosts/MyPosts';
export {default as Post} from './Post/Post';
export {default as AllPosts} from './AllPosts/AllPosts';
export {default as NavBar2} from './NavBar2/NavBar2';
